sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: guo197268!
  alioss:
    endpoint: oss-us-west-1.aliyuncs.com
    access-key-id: LTAI5tByvLAWx9yoCV2ERfve
    access-key-secret: kn25yCIydsI5c1Ct8azJ0r9AAbCsaz
    bucket-name: xigbucket
  redis:
    host: localhost
    port: 6379
    password: guo197268!
    database: 10
  wechat:
    appid: wxb3753b9182899b80
    secret: 5d954465cb82a1660972e472be16fc16